# Generated by Django 5.1.3 on 2024-11-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantor_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='currency_form',
            new_name='currency_from',
        ),
    ]
